<?php

/**
 * @file createAPageWithTemplate.module.
 */

/**
 * Implementation of hook_menu()
 */
function createAPageWithTemplate_menu() {
	$items['aNewPage'] = array(
		'access callback' => 'node_access', // change the callback for the access control
		'access arguments' => array('view',1),
	 	'page callback' 	=> 'a_new_page_callback',
		'type' => MENU_CALLBACK,
	);

	return $items;
}

/**
 * Page callback: displaying a page with php template
 *  
 * @see createAPageWithTemplate_menu()
 */
function a_new_page_callback($test_parameter1 = 'hello', $test_parameter2 = ' world'){
  drupal_add_css(drupal_get_path('module', 'createAPageWithTemplate') . '/css/anewpage.css');

  global $user;
  $build = array();

  if (isset($test_parameter1))
   print_r($test_parameter1);

  if (isset($test_parameter2))
   print_r($test_parameter2);

  $uid = 1;
  $result=db_query("SELECT nid, created FROM {node} WHERE uid = :uid", array(':uid' => $uid));
  $records = $result->fetchAll();
  //print_r($record);
  var_dump(records);

  $query = db_select('node','n')->fields('n');
  $records = $query->execute()->fetchAll();
  var_dump(records);
  
  $query = db_select('node', 'n')->extend('PagerDefault');
  $nids = $query
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('type', 'blog')
    ->condition('status', 1)
    ->orderBy('sticky', 'DESC')
    ->orderBy('created', 'DESC')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build += node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
  }
  else {
    drupal_set_message(t('No blog entries have been created.'));
  }

  $title = t("A New Page for Testing");
	$variables = array('title' => $title, 'contents' => drupal_render($build));
	return theme('a_testing_page', $variables);
}

/**
 * Implements hook_theme().
 */
function createAPageWithTemplate_theme() {
  return array(
    'a_testing_page' => array(
      'variables' => array('title' => NULL, 'contents' => NULL),
      'template' => 'a-testing-page',
    ),
  );
}

/**
 * Processes variables for book-export-html.tpl.php.
 *
 * @param $variables
 *   An associative array containing the following keys:
 *   - title
 *   - contents
 *
 * @see a-testing-page.tpl.php
 */
function template_preprocess_a_testing_page(&$variables) {
  $variables['title'] = check_plain($variables['title']);
  $imgpath = drupal_get_path('module', 'createAPageWithTemplate') . '/css/bd_logo1.png';
  $variables['logo'] = file_create_url($imgpath);
}
